package helper

const (
	RESTY_PAGE    = "RESTY_PAGE"
	HEADER_DIALOG = "HEADER_DIALOG"
	FORM_DIALOG   = "HEADER_FORM_DIALOG"

	NAVIGATION_PAGE = "NAVIGATION_PAGE"

	ENVIRONMENT_PAGE = "ENVIRONMENT_PAGE"
)
